In [1]:
import duckdb

con = duckdb.connect("/home/nvmaxim/Projects/moscow-transport-pipeline/data/transport.db")
con.execute("SELECT * FROM routes LIMIT 10").df()

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,route_sort_order,continuous_pickup,continuous_drop_off
0,100457-1229,100457-1,н4,Новокосино - Метро «Китай-город»,None,3,None,None,None,None,None,None
1,100457-202,100457-1,279,2-й микрорайон Жулебина - Метро «Нижегородская»,None,3,None,None,None,None,None,None
2,100457-585,100457-1,149,Коровино - МЦД Дегунино,None,3,None,None,None,None,None,None
3,100457-392,100457-1,1002,Киевский - Метро «Саларьево»,None,3,None,None,None,None,None,None
4,100457-214,100457-1,111,Улица Новаторов - Метро «Октябрьская»,None,3,None,None,None,None,None,None
5,100457-104,100457-1,135,Метро «Парк Победы» - Ул. Акад. Павлова,None,3,None,None,None,None,None,None
6,100457-328,100457-1,196,Тропарёво - Метро «Октябрьская»,None,3,None,None,None,None,None,None
7,100457-416,100457-1,32,МЦД Мещерская - Метро «Рассказовка»,None,3,None,None,None,None,None,None
8,100457-624,100457-1,40,Дворец спорта «Сокольники» - Дворец спорта «Со...,None,3,None,None,None,None,None,None
9,100457-853,100457-1,69,Парк «Фили» - Метро «Краснопресненская»,None,3,None,None,None,None,None,None

In [ ]:
# Все таблицы
con.execute("SHOW TABLES").df()

         name
0      agency
1    calendar
2      routes
3  stop_times
4       stops
5       trips

In [8]:
# Структура конкретной таблицы (колонки, типы)
con.execute("DESCRIBE stops").df()

            column_name column_type null   key default extra
0               stop_id     VARCHAR  YES  None    None  None
1             stop_code     VARCHAR  YES  None    None  None
2             stop_name     VARCHAR  YES  None    None  None
3             stop_desc     VARCHAR  YES  None    None  None
4              stop_lat      DOUBLE  YES  None    None  None
5              stop_lon      DOUBLE  YES  None    None  None
6               zone_id     VARCHAR  YES  None    None  None
7              stop_url     VARCHAR  YES  None    None  None
8         location_type      BIGINT  YES  None    None  None
9        parent_station     VARCHAR  YES  None    None  None
10        stop_timezone     VARCHAR  YES  None    None  None
11  wheelchair_boarding      BIGINT  YES  None    None  None
12             level_id     VARCHAR  YES  None    None  None
13        platform_code     VARCHAR  YES  None    None  None

In [9]:
# Структура всех таблиц сразу
for table in con.execute("SHOW TABLES").fetchall():
    t = table[0]
    print(f"\n=== {t} ===")
    display(con.execute(f"DESCRIBE {t}").df())

=== agency ===

       column_name column_type null   key default extra
0        agency_id     VARCHAR  YES  None    None  None
1      agency_name     VARCHAR  YES  None    None  None
2       agency_url     VARCHAR  YES  None    None  None
3  agency_timezone     VARCHAR  YES  None    None  None
4      agency_lang     VARCHAR  YES  None    None  None
5     agency_phone     VARCHAR  YES  None    None  None
6  agency_fare_url     VARCHAR  YES  None    None  None
7     agency_email     VARCHAR  YES  None    None  None

=== calendar ===

  column_name column_type null   key default extra
0  service_id     VARCHAR  YES  None    None  None
1      monday      BIGINT  YES  None    None  None
2     tuesday      BIGINT  YES  None    None  None
3   wednesday      BIGINT  YES  None    None  None
4    thursday      BIGINT  YES  None    None  None
5      friday      BIGINT  YES  None    None  None
6    saturday      BIGINT  YES  None    None  None
7      sunday      BIGINT  YES  None    None  None
8  start_date      BIGINT  YES  None    None  None
9    end_date      BIGINT  YES  None    None  None

=== routes ===

            column_name column_type null   key default extra
0              route_id     VARCHAR  YES  None    None  None
1             agency_id     VARCHAR  YES  None    None  None
2      route_short_name     VARCHAR  YES  None    None  None
3       route_long_name     VARCHAR  YES  None    None  None
4            route_desc     VARCHAR  YES  None    None  None
5            route_type      BIGINT  YES  None    None  None
6             route_url     VARCHAR  YES  None    None  None
7           route_color     VARCHAR  YES  None    None  None
8      route_text_color     VARCHAR  YES  None    None  None
9      route_sort_order     VARCHAR  YES  None    None  None
10    continuous_pickup     VARCHAR  YES  None    None  None
11  continuous_drop_off     VARCHAR  YES  None    None  None

=== stop_times ===

            column_name column_type null   key default extra
0               trip_id     VARCHAR  YES  None    None  None
1          arrival_time     VARCHAR  YES  None    None  None
2        departure_time     VARCHAR  YES  None    None  None
3               stop_id     VARCHAR  YES  None    None  None
4         stop_sequence      BIGINT  YES  None    None  None
5         stop_headsign     VARCHAR  YES  None    None  None
6           pickup_type     VARCHAR  YES  None    None  None
7         drop_off_type     VARCHAR  YES  None    None  None
8     continuous_pickup     VARCHAR  YES  None    None  None
9   continuous_drop_off     VARCHAR  YES  None    None  None
10  shape_dist_traveled     VARCHAR  YES  None    None  None
11            timepoint      BIGINT  YES  None    None  None

=== stops ===

            column_name column_type null   key default extra
0               stop_id     VARCHAR  YES  None    None  None
1             stop_code     VARCHAR  YES  None    None  None
2             stop_name     VARCHAR  YES  None    None  None
3             stop_desc     VARCHAR  YES  None    None  None
4              stop_lat      DOUBLE  YES  None    None  None
5              stop_lon      DOUBLE  YES  None    None  None
6               zone_id     VARCHAR  YES  None    None  None
7              stop_url     VARCHAR  YES  None    None  None
8         location_type      BIGINT  YES  None    None  None
9        parent_station     VARCHAR  YES  None    None  None
10        stop_timezone     VARCHAR  YES  None    None  None
11  wheelchair_boarding      BIGINT  YES  None    None  None
12             level_id     VARCHAR  YES  None    None  None
13        platform_code     VARCHAR  YES  None    None  None

=== trips ===

             column_name column_type null   key default extra
0               route_id     VARCHAR  YES  None    None  None
1             service_id     VARCHAR  YES  None    None  None
2                trip_id     VARCHAR  YES  None    None  None
3          trip_headsign     VARCHAR  YES  None    None  None
4        trip_short_name     VARCHAR  YES  None    None  None
5           direction_id      BIGINT  YES  None    None  None
6               block_id     VARCHAR  YES  None    None  None
7               shape_id     VARCHAR  YES  None    None  None
8  wheelchair_accessible     VARCHAR  YES  None    None  None
9          bikes_allowed     VARCHAR  YES  None    None  None